---
name: AppDaemonDbus
version: dev
slug: appdaemon_dbus
description: Appdaemon with D-Bus support
url: https://github.com/hassio-addons/addon-appdaemon
codenotary: codenotary@frenck.dev
webui: http://[HOST]:[PORT:5050]
arch:
  - aarch64
  - amd64
  - armv7
init: false
homeassistant_api: true
uart: true
ports:
  5050/tcp: 5050
ports_description:
  5050/tcp: AppDaemon
devices:
  - "/dev/bus/usb:/dev/bus/usb:rwm"
map:
  - addon_config:rw
  - homeassistant_config:rw
  - media:rw
  - share:rw
  - ssl
  - dbus
options:
  system_packages: []
  python_packages: []
  init_commands: []
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  system_packages:
    - str
  python_packages:
    - str
  init_commands:
    - str
